title: Wopslang
description: > # this means to ignore newlines until "baseurl:"
  Wopslang Blog 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://wopslang.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Wops Team'
  last_name: 'Wops Team'
  avatar: '/images/avatar.jpeg'
  github_username:  Wopslang
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


